### PR TITLE
added query for local admin groups

### PR DESCRIPTION
**Pull request by alexverboon**
I have added a query to find changes to local admin groups, see this blog post for more details. https://www.verboon.info/2020/09/hunting-for-local-group-membership-changes/

### CODE REVIEW

**Review by tali-ash — CHANGES_REQUESTED** [review]
Interesting blog and query! 

Can you please suggest the filtering:
// limit to local administrators group
// | where LocalGroupSID contains "S-1-5-32-544"

before the join(move it to be before the first join line), when query DeviceEvents to reduce left side of the join, so the join will be more efficient.

**Comment by alexverboon** [comment]
Hi, I will work on the change in the next 2 days and then send an update

**Comment by alexverboon** [comment]
Hello @tali-ash , i've updated the query as suggested.

**Comment by alexverboon** [comment]
I have updated the query , can you check?

**Review by tali-ash — APPROVED** [review]

**Pull request merged**
